"""Created a function to update the last_edited timestamp column, and created a trigger to call this function for the products table.

Revision ID: 172f9e67a364
Revises: eebe110ef9d2
Create Date: 2026-02-08 16:41:47.178179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = '172f9e67a364'
down_revision: Union[str, None] = 'eebe110ef9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_timestamp_update_on_edit = PGFunction(
        schema="public",
        signature="timestamp_update_on_edit()",
        definition='RETURNS TRIGGER AS $$ BEGIN NEW.last_edited = now();\nRETURN NEW;\nEND;\n$$ language PLPGSQL'
    )
    op.create_entity(public_timestamp_update_on_edit)

    public_products_timestamp_update_apply_products_trigger = PGTrigger(
        schema="public",
        signature="timestamp_update_apply_products_trigger",
        on_entity="public.products",
        is_constraint=False,
        definition='BEFORE \nUPDATE \n  on products FOR EACH ROW EXECUTE FUNCTION timestamp_update_on_edit()'
    )
    op.create_entity(public_products_timestamp_update_apply_products_trigger)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_products_timestamp_update_apply_products_trigger = PGTrigger(
        schema="public",
        signature="timestamp_update_apply_products_trigger",
        on_entity="public.products",
        is_constraint=False,
        definition='BEFORE \nUPDATE \n  on products FOR EACH ROW EXECUTE FUNCTION timestamp_update_on_edit()'
    )
    op.drop_entity(public_products_timestamp_update_apply_products_trigger)

    public_timestamp_update_on_edit = PGFunction(
        schema="public",
        signature="timestamp_update_on_edit()",
        definition='RETURNS TRIGGER AS $$ BEGIN NEW.last_edited = now();\nRETURN NEW;\nEND;\n$$ language PLPGSQL'
    )
    op.drop_entity(public_timestamp_update_on_edit)

    # ### end Alembic commands ###
